version: "3.4"

services:
  pwa-nginx:
    container_name: pwa-nginx
    build: pwa-nginx/
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    environment:
      - SERVER_NAME="MERCI DE REMPLACER LE SERVER_NAME, MERCI !!"
      - CERT_FULLCHAIN="/etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem"
      - CERT_PRIVKEY="/etc/letsencrypt/live/${SERVER_NAME}/privkey.pem"
    # Command is used to substitute env variables from the nginx conf
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - pwa-front
      - pwa-api
      - pwa-postgres
      - pwa-certbot
    networks:
      - pwa-front
      - pwa-api
      - pwa-postgres

  pwa-front:
    container_name: pwa-front
    build: pwa-project/
    environment:
      - PORT=8000
    networks:
      - pwa-front

  pwa-api:
    container_name: pwa-api
    build: pwa-api/
    networks:
      - pwa-api
      - pwa-postgres

  pwa-postgres:
    image: postgres:latest
    volumes:
      - ./data/postgres:/opt/postgres/data
    environment:
      - POSTGRES_USER="manager"
      - POSTGRES_PASSWORD="admin"
      - POSTGRES_DB="pwa"
    networks:
      - pwa-postgres

  pwa-certbot:
    image: certbot/certbot
    container_name: pwa-certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot
    entrypoint: sh -c "while :; do certbot renew; sleep 12h; done"
    networks:
      - pwa-certbot

networks:
  pwa-front:
  pwa-api:
  pwa-postgres:
  pwa-certbot:
