version: "3.4"

services:
  pwa-nginx:
    environment:
      - SERVER_NAME=localhost
  
  pwa-front:
    build:
      context: website/
      target: front-install
    command: sh -c "npm run start"
    environment:
      - SERVER_NAME=localhost
    volumes:
      - ./website/src:/app/src:ro

  # No specific build for the API
  # Maybe install `nodemon` for hotreload the api

  pwa-certbot:
    image: alpine # Small image since we don't want certbot in dev
    entrypoint: sh -c ""

